# Dockerfile.runtime
FROM ds-base:1.0

COPY ./hadoop-3.3.3 /data/service/hadoop
COPY ./zulu8.68.0.21-ca-jdk8.0.362-linux_x64 /data/service/java8
COPY ./lcc-hook-2.0 /data/service/lcc-hook
COPY ./spark-3.3.2-hive2.3.7-without-hadoop-bin /data/service/spark-3.3.2

ENV SPARK_HOME=/data/service/spark-3.3.2
ENV JAVA_HOME=/data/service/java8
ENV HADOOP_HOME=/data/service/hadoop
ENV PATH=$SPARK_HOME/bin:$JAVA_HOME/bin:$HADOOP_HOME/bin:$PATH