# Dockerfile.base
FROM openjdk:8

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y krb5-user libpam-krb5 cron && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN groupadd dolphinscheduler && \
    useradd -m -g dolphinscheduler dolphinscheduler