apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.129.88.8
    path: /srv/nfs/data
  persistentVolumeReclaimPolicy: Retain