apiVersion: v1
kind: Pod
metadata:
  name: nfs-test-pod
spec:
  containers:
    - name: writer
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          while true; do echo "$(date) Hello from NFS!" >> /mnt/logs/demo.log; sleep 5; done
      volumeMounts:
        - mountPath: /mnt/logs
          name: nfs-vol
  volumes:
    - name: nfs-vol
      persistentVolumeClaim:
        claimName: demo-nfs-pvc